update dialect xsd up to date
tableau/connector-plugin-sdk pull request #815
Opened 2021-07-15 18:36 UTC by jsun28

Update this dialect xsd as latest near, changes are from near file history 6-10(5 revisions in total)

2021-07-15 19:59 UTC, rosswbrown requested changes
Some of these will be in 2021.3 and others 2021.4.

Once master has been updated to 2021.2, we'll create 2021.3 and .4 branches here.

2021-07-21 19:39 UTC, jsun28 commented
> Some of these will be in 2021.3 and others 2021.4.
> 
> Once master has been updated to 2021.2, we'll create 2021.3 and .4 branches here.

Thanks, I changed the target branch to dev-2021.3, and looks like only revision 10 in near is not in dev-2021.3, so removed that change.

2021-07-21 21:08 UTC, rosswbrown reviewed
I noticed we added this version comment in some other new addition.  Seems handy, we'll see if we can keep it up for now.

2021-07-21 21:08 UTC, rosswbrown commented on validation/tdd_latest.xsd
> +          <xs:attribute name="value" type="xs:string" />
```suggestion
          <xs:attribute name="value" type="xs:string" /> <!-- added 2020.3 -->
```

2021-07-21 21:08 UTC, rosswbrown commented on validation/tdd_latest.xsd
> +      <xs:element minOccurs="0" name="start-of-week-format" type="StartOfWeekFormat-CT"/>
```suggestion
      <xs:element minOccurs="0" name="start-of-week-format" type="StartOfWeekFormat-CT"/> <!-- added 2021.3 -->
```

2021-07-21 21:08 UTC, rosswbrown commented on validation/tdd_latest.xsd
> +      <xs:enumeration value="IF"/>
```suggestion
      <xs:enumeration value="IIF_"/> <!-- added 2021.3 -->
      <xs:enumeration value="IF"/> <!-- added 2021.3 -->
```

2021-07-21 21:08 UTC, rosswbrown commented on validation/tdd_latest.xsd
> +          <xs:attribute name="value" type="xs:string" />
This should say 2021.3

2021-07-21 22:23 UTC, sxlin approved these changes
Ship it after add the comments Ross suggested.

2021-07-22 02:48 UTC, jsun28 commented
> I noticed we added this version comment in some other new addition. Seems handy, we'll see if we can keep it up for now.

Added comments as you suggested, and I tested it with packager, validation is working fine.

2021-07-22 16:36 UTC, rosswbrown approved these changes

2021-07-22 17:14 UTC, merged