OS region setting requirements for TDVT test
tableau/connector-plugin-sdk pull request #934
Opened 2022-03-22 19:01 UTC by tabBhargav

**Things To Remember:** 

1. Be sure to merge into the right branch. The choices are:
* **`master`** if your PR runs on the current version of Tableau.
* **`dev-2021.2`**  
2. You should update at least one of the following:
* The changelog of the project you modified.
* The root `README.md` if the PR is a release of the SDK, Connector Packager, or TDVT.  
=====

2022-03-22 20:34 UTC, rosswbrown commented
It is the TDVT expected files that require that format correct?

Also I'm not sure documentation should recommend modifying the test date.

I noticed there is a bit of a troubleshooting [section](https://tableau.github.io/connector-plugin-sdk/docs/tdvt-test-case#triaging-a-specific-tdvt-test-case) here too, but this file seems to be the primary location.

2022-07-18 18:38 UTC, lukewrites requested changes

2022-07-18 18:38 UTC, lukewrites commented on docs/tdvt.md
> +Another workaround is to check that all tests should store input dates (times and datetimes) in the save format as CSV has. Otherwise the format should be hardcoded to match the CSV or, better, defin
Let's leave out t he below. Just say what's in line 549

2022-07-26 17:33 UTC, lukewrites commented on docs/tdvt.md
> +__The date string format vary according to OS date format settings__
```suggestion
__Date string format varies according to OS date format settings__
```

2022-07-26 17:33 UTC, lukewrites approved these changes
🚢

2022-07-26 17:34 UTC, merged