Sdavis string tests
tableau/connector-plugin-sdk pull request #979
Opened 2022-06-29 17:10 UTC by tabsdavis

Added string tests from unittests.

2022-07-06 17:35 UTC, lukewrites requested changes
A few changes to make then run another proof and see if it helps.

2022-07-06 17:35 UTC, lukewrites commented on tdvt/tdvt/exprtests/standard/expected.setup.string.endswith.null.txt
> +      Reference to undefined field Num0.&#10;Perhaps you meant [num0]?&#10;&#10;    </error>
We don't want to check in an error as an expected. If a ds doesn't support this test we can add the test case to the excludes list in the ds's .ini file.

2022-07-06 17:35 UTC, lukewrites commented on tdvt/tdvt/exprtests/standard/setup.string.endswith.null.txt
> +ENDSWITH(Num0, Null)
Some of the col names start with an uppercase letter, others with lowercase. In tests/datasets/TestV1/postgres/load_calcs.sql I see that the cols are all named using lowercase. Were these conventions in the tests on the monolith? You could try changing them to lowercase (in this file and others) and then doing the proof run.

2022-07-06 17:35 UTC, lukewrites commented on tdvt/tdvt/exprtests/standard/setup.string.find.null.txt
> +find(Int0, Null)
Same as above - `int0` rather than `Int0`?

2022-07-06 17:35 UTC, lukewrites commented on tdvt/tdvt/exprtests/standard/setup.string.startswith.null.txt
> +STARTSWITH(Num0, Null)
same for the above - if I'm missing something about this let me know

nit: can remove the blank lines below, too

2022-07-18 18:01 UTC, rosswbrown commented on tdvt/tdvt/exprtests/standard/setup.string.endswith.null.txt
> +ENDSWITH(num0, Null)
```suggestion
ENDSWITH(str1, Null)
```
I think all of these tests should use str1 (no null values) and str2 (null values). An int or num column is out of scope for the string tests.

Its possible all the same coverage can be achieved in these tests by just running test cases on str2

2022-07-18 18:02 UTC, rosswbrown commented on tdvt/tdvt/exprtests/standard/setup.string.startswith.null.txt
> +STARTSWITH(num0, Null)
```suggestion
STARTSWITH(str2, Null)
```
Please let me know if I'm missing why num0 and int0 were added.

2022-07-22 22:42 UTC, lukewrites commented
Closing, these changes are included in #969

2022-07-22 22:42 UTC, closed without merging